### ISSUE TITLE
feat: User 기능 개발

### ISSUE THREAD

**Issue by NARUBROWN** [Blooming-TF/CodingLand-BE#10]
# Title

- User 기능 개발

# TODO

- [x] 등록된 유저를 모두 조회하는 기능
- [x] 유저 수정 기능
- [x] 활동포인트 증가 기능
- [x] 활동포인트 감소 기능
- [x] 활동포인트 조회 기능
- [x] 기초트레이닝 완료처리 기능
# etc

- nothing
