### ISSUE TITLE
feat: 인증 기능 구현

### ISSUE THREAD

**Issue by Jeongh00** [Blooming-TF/CodingLand-BE#4]
# Title

- 인증 기능 + User API 구현

# TODO

- [x] 인증 @AuthenticationPrincipal 설정
- [ ] User API 관련 기능 구현
- [x] 예외처리 통일
- [ ] @Service annotation 으로 기능 분리

# etc

- nothing
